server:
  port: 4000
spring:
  application:
    name: Security-JDBC-Authention
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/jdbcauth
    username: root
  jpa:
    show-sql: true
